- hosts: "localhost"
  vars_files: "secret.yml"
  vars_prompt:
          - name: "num_item"
            prompt: "enter the number of backened servers"
            private: no 
  tasks:
          - name: "provisioning the instances "
            ec2:
                    zone: "ap-south-1a"
                    wait: yes
                    assign_public_ip: "yes"
                    ec2_access_key: "{{ u }}"
                    ec2_secret_key: "{{ p }}"
                    instance_tags:
                            Name: "{{ item.name }}"
                    count: "{{ item.num }}"
                    image: "ami-04b1ddd35fd71475a"
                    instance_type: "t2.micro"
                    key_name: "hadoop_slave_key"
                    region: "ap-south-1"
                    wait: yes
                    vpc_subnet_id: "subnet-678b820f"
            loop:
                    - { name: 'webserver', num: "{{ num_item }}" }
                    - { name: 'loadbalancer', num: 1 }
          - meta: refresh_inventory
          - pause:
                  seconds: 30


- hosts: "tag_Name_loadbalancer"
  roles:
          - role: "loadbalancer"
- hosts: "tag_Name_webserver"
  roles:
          - role: "myapache"
